name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: debugging
      run: ls
    - name: Install Dependencies
      run: pip install -e '.[development]'
    - name: Run Pytest
      run: tox

  linter:
      name: Precommit Validations
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: pip install -e '.[development]'